### ISSUE TITLE
Issue 6 for Milestone 3: Training the Model

### ISSUE THREAD

**Issue by UnikaMureithi** [UnikaMureithi/BI_Project#6]
- [x] Data splitting
- [x] Cross validation (basic, repeated or LOOCV)
- [x] Bootstrapping
- [x] Model training for either classification, regression, association or clustering (as applicable)
- [x] Model performance comparison using resamples (for classification and regression)

**Comment by UnikaMureithi** [comment]
The model was trained for classification. After one hot encoding was undertaken.
The dataset was split into a training set and a testing set
